spring.application.name=vibecheck

# Database Connection with Environment Variables & Local Fallbacks
spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:postgresql://aws-1-ap-southeast-2.pooler.supabase.com:6543/postgres?sslmode=require&prepareThreshold=0}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:postgres.jgxooahsjrgdvrqrxjpm}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:$N3!Lrk5z_fT/g+}
spring.datasource.driver-class-name=org.postgresql.Driver

# Hibernate properties
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# Critical for Deployment (Render needs dynamic PORT)
server.port=${PORT:8080}

# JWT Secret
jwt.secret=${JWT_SECRET:A_Very_Long_Super_Secret_Key_For_JWT_Signing_Must_Be_At_Least_32_Bytes}